package at.fh.swengb.beFast.drops.recyclerview

import android.content.Context
import at.fh.swengb.beFast.drops.DescriptionNote
import at.fh.swengb.beFast.drops.dao.DescriptionNoteDB
import at.fh.swengb.beFast.models.drops.Drops

//val id0: String = Context.getString(R.string.id0)

    //val id0: String = getSystem().getString(R.string.id0)

object DropsRepository {

    //val id0: String = Resources.getSystem().getString(R.string.id0)


    val drops: List<Drops> = listOf(
            Drops("0","Nike", "Air Force 1 Rayguns", "05.02.2021 +0100 09:00", "120€", "https://stockx.imgix.net/images/Nike-Air-Force-1-Low-Raygun.png?fit=fill&bg=FFFFFFhttps://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2021%2F01%2Fadidas-zx-5000-vieux-lyon-jacquard-release-details-05.jpg?q=75&w=800&cbr=1&fit=max","https://www.nike.com/de/launch?s=upcoming","https://stockx.com/de-de/nike-air-force-1-low-raygun", "Mit den Sneakern aus der Rayguns Kollektion hat Nike damals eine unglaublich gute Story drum herum erschaffen, die sich um eine Fantasie-Basketballmannschaft im Weltall drehte. Mit aufwendigen Videos und coolen Marketingaktionen, kam der Nike Dunk damals auf den Markt, nun stehen zwei weitere Releases unter der Rayguns-Flagge bevor. Neben dem Kyrie 7 erwartet uns mit dem Air Force 1 ein echter Klassiker, welcher der Thematik unterzogen wurde."),
            Drops("1","Supreme","Cross Box Logo Tee Red","06.02.2021 +0100 12:00","60€","https://stockx.imgix.net/images/Supreme-Cross-Box-Logo-Tee-Red.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1608222060&w=1000","https://www.supremenewyork.com","https://stockx.com/de-de/supreme-cross-box-logo-tee-red","Just two weeks after dropping them in hoodie form, Supreme has returned to release a t-shirt version of their highly-anticipated Cross Box Logo. This red Supreme Cross Box Logo t-shirt feature's two of the brand's popular box logos laid over one another in the shape of a cross. The Supreme Cross Box Logo t-shirt was released as a part of the brand's FW20 winter tees collection which also included the Mariah Carey t-shirt."),
            Drops("2","Puma","XT2+ Hanon","06.02.2021 +0100 12:00","80€","https://stockx.imgix.net/Puma-XT2-Hanon-Adventurer-Pack.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1603481985&w=1000","https://eu.puma.com/at/de/home","https://stockx.com/de-de/puma-xt2-hanon-adventurer-pack","The Adventurer edition of the XT2 is inspired by the early days travelling overseas, from the winter gloom in Scotland to the sunshine warmth of California. Executed in a lush pig suede application, the colours reference the stark contrast  in weather whilst  a ‘memories’  print is featured on the lining."),
            Drops("3","Adidas", "ZX 5000 Vieux Lyon", "07.02.2020 +0100 11:00", "120€", "https://stockx.imgix.net/images/adidas-ZX-5000-Vieux-Lyon.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1609866973&w=1000","https://www.adidas.at","https://stockx.com/de-de/adidas-zx-5000-vieux-lyon","Die A-ZX-Serie geht in die nächste Runde und hält einen ZX 5000 für uns bereit. Der Buchstabe V aus dem A-ZX-Alphabet ist der französischen Stadt Vieux Lyon gewidmet, aus der ursprünglich das bekannte Jaquard Muster stammt. Aus diesem Grund wurde auch der ZX 8000 mit den aufwendigen Stickereien versehen, die sich in verschiedenen Farben über den gesamten Sneaker zeihen. Der untere Bereich ist dabei mit dem Stoff in einem kühlen Grau bezogen und der obere Bereich ist in auffälligem Violett gehalten. "),
            Drops("4","Fear of God","Sail Black","07.02.2020 +0100 12:00","380€","https://stockx-360.imgix.net/Nike-Air-Fear-Of-God-1-Sail-Black/Images/Nike-Air-Fear-Of-God-1-Sail-Black/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1608522448&w=1000","https://www.nike.com/de/launch?s=upcoming","https://stockx.com/de-de/nike-air-fear-of-god-1-sail-black","Sail away while wearing the Air Fear Of God 1 Sail Black. This Air FOG 1 comes with a sail upper, black Nike “Swoosh”, sail midsole, and translucent sole. These sneakers were released in June 2019 and retailed for $350. BeFast for the next drop!"),
            Drops("5","New Balance","670 Year of the Rat","08.02.2020 +0100 09:00","150€","https://stockx.imgix.net/New-Balance-670-Year-of-the-Rat-2020.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1603481985&w=1000","https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwih9O3-o4zuAhUY7u0KHT8yCMUYABARGgJkZw&ohost=www.google.at&cid=CAESQOD2NDDJ9mnh5Wj20ooFLlW8TyGEpWuzyRAUGq852aIX7fH6Z4blfSj3RPuEyabhJb6ja-Hod5jCb7_GCR37Kxg&sig=AOD64_3LsCX32axTa8BBwJyN6IZ7QQzlig&q&adurl&ved=2ahUKEwjyhuT-o4zuAhWfaRUIHTtVASUQ0Qx6BAgGEAE","https://stockx.com/de-de/new-balance-670-year-of-the-rat-2020","Designed to interpret the colors found on the Husky Rat breed, this latest version dyes its nubuck and pigskin-engineered upper with nude and grey hues to mirror elements of its fur. Complementing tones of pink are additionally added into the forefoot overlays to translate the rodent’s other features such as its ears, paws, and tail, which ultimately result in a much brighter approach to its collection sibling."),
            Drops("6","Nike","Nike Lebron 18 Kylian Mbappe","08.02.2020 +0100 09:00","185€","https://stockx.imgix.net/images/Nike-Lebron-18-Kylian-Mbappe.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1609866953&w=1000","https://www.nike.com/de/launch?s=upcoming","https://stockx.com/de-de/nike-lebron-18-kylian-mbappe","Der berühmte Stürmer von Paris Saint Germain, Kylian Mbappe, hilft Lebron James bei seinem 18. Signature-Sneaker. Die beiden Freunde veröffentlichen nämlich gemeinsam einen kollaborativen Sneaker. Der Court-Sneaker kommt mit einem eher futuristischen Look, der ein schwarzes Knitposite 2.0-Obermaterial erhält, das die Stadt Frankreich mit roten und blauen Verzierungen ehrt. Silberne Zungen sowie ein durchscheinender Fersenclip und eine schillernde Gummilaufsohle runden den brandneuen Look ab."),
            Drops("7","Nike","Air Force 1 Low Orange Skeleton","08.02.2020 +0100 09:00","89,99€","https://stockx.imgix.net/images/Nike-Air-Force-1-Low-Orange-Skeleton-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1609438989","https://www.nike.com/de/launch?s=upcoming","https://stockx.com/de-de/nike-air-force-1-low-orange-skeleton","The Nike Air Force 1 Orange Skeleton comes dressed in an all-orange leather upper with a skeleton x-ray print on each side of the upper. Similar to the candle-lit glow of a Jack-O-Lantern, this release features a glow-in-the-dark translucent sole that is geared to light up your step. Glossy black lace tags, Nike Air branding on the tongue, and a skeleton printed insole complete this spooky AF1."),
            Drops("8","Nike","Dunk High Ambush Active","10.02.2020 +0100 09:00","180€","https://stockx.imgix.net/images/Nike-Dunk-High-Ambush-Active-Fuchsia.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1609406830&w=1000","https://www.nike.com/de/","https://stockx.com/de-de/nike-dunk-high-ambush-active-fuchsia?utm_source=af&utm_medium=imp&utm_campaign=2089136&impactSiteId=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5QT6lWRRXU0&clickid=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5QT6lWRRXU0&utm_term=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5QT6lWRRXU0&utm_content=_530344&irgwc=1","Der erste Colorway des Ambush Nike Dunk High ist bereits vor einigen Wochen erschienen, nun erscheint der bereits lang angeteaserte Lethal Pink. Yoon ist für ihre kreative und individuelle Herangehensweise bekannt und dies zeigte sie wieder einmal auf ihrem eigenen Dunk High."),
            Drops("9","Nike","Air Jordan 1 High OG Gold", "10.02.2020 +0100 09:00","160€","https://stockx.imgix.net/images/Air-Jordan-1-Retro-High-White-Black-Volt-University-Gold.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1605645198&w=1000","https://www.nike.com/de/launch?s=upcoming","https://stockx.com/de-de/air-jordan-1-retro-high-white-black-volt-university-gold?utm_source=af&utm_medium=imp&utm_campaign=2089136&impactSiteId=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5hRilWRRXU0&clickid=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5hRilWRRXU0&utm_term=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5hRilWRRXU0&utm_content=_530344&irgwc=1","Das Jahr startet wieder mit richtig starken Colorways auf dem Jordan 1 High! Der beliebte Sneaker bekommt eine Farbkombination aus Schwarz, Weiß, Neongelb und gelbgoldenen Details. Bei der Materialauswahl wurde auf hochwertiges Glattleder gesetzt. Zudem hat der Sneaker leichte Vintage-Momente, durch die Schaumstoffzunge. Die Farbe des Schaumstoffs ist ebenfalls goldgelb und passt somit optimal zur Farbe der Heel."),
            Drops("10","Nike","Air Max 97 Sail","12.02.2020 +0100 09:00","180€","https://stockx.imgix.net/images/Nike-Air-Max-97-Undefeated-UCLA.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1609455487&w=1000","https://www.nike.com/de/launch?s=upcoming","https://stockx.com/de-de/nike-air-max-97-undefeated-ucla?utm_source=af&utm_medium=imp&utm_campaign=2089136&impactSiteId=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5mzalWRRXU0&clickid=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5mzalWRRXU0&utm_term=0wTzeIXuvxyOWzVwUx0Mo3EAUkEy5mzalWRRXU0&utm_content=_530344&irgwc=1","Der Air Max 97 war noch nie ein besonders subtiler Sneaker. Die mehrschichtige Wellen-Ästhetik und das durchgehende, sichtbare Air-Element waren schon bei seiner Veröffentlichung ein wahrer Blickfang. Auch 20 Jahre später ist das Design des Schuhs, bei dem im Hinblick auf das lässige gewellte Obermaterial nochmal nachgelegt wurde, noch immer markant. ")

    )

    fun dropById(id: String): Drops? {
        return drops.find { it.id == id }
    }
    fun addDescriptionNote(context: Context, descriptionNote: DescriptionNote) {
        val applicationContext = context.applicationContext
        val db = DescriptionNoteDB.getDatabase(applicationContext)
        db.descriptionNoteDao.insert(descriptionNote)
    }
    fun findSameID(context: Context, id: String): DescriptionNote {
        val applicationContext = context.applicationContext
        val db = DescriptionNoteDB.getDatabase(applicationContext)
        return db.descriptionNoteDao.findDropBySameID(id)
    }
}